sources:
  - name: test_app
    database: test_app
    schema: scooter_raw
    tables:
      - name: trips
        meta:
          docs:
            node_color: "#f8f9fa"
            node_outline: "#dadce0"
      - name: users
        meta:
          docs:
            node_color: "#f8f9fa"
            node_outline: "#dadce0"
      - name: events
        meta:
          docs:
            node_color: "#f8f9fa"
            node_outline: "#dadce0"