sources:
  - name: test_app
    database: test_app
    schema: scooter_raw
    tables:
      - name: trips
      - name: users
      - name: events

    +docs:
      node_color: "#f8f9fa"
      node_outline: "#dadce0"